In [1]:
# import python lib
import pandas as pd
# set import path to my py
import sys
sys.path.append("..")
import hqop
from hqscan import HqScanResult, HqCsvRepo

In [2]:
# hqrobot download
#from io import StringIO
#csv = hqRobot.hqGet("VSTM", startDate, today)
#csv = csv.decode("utf-8")
#print(csv[0:100])
#vstm = pd.DataFrame(StringIO(csv.decode("utf-8")))
#vstm.head()

In [11]:
# read hqscan result
# LLBCP Last 2 Day
df = pd.read_csv('../' + HqScanResult, header=0, index_col=[0])
df[df.HqType == 'LLBCP2'].sort_values(by='CCChg', ascending=False)

  Symbol  HqType        Date  No  HqTypeChg     CCChg    MetaInfo
2   BCRX  LLBCP2  2021-02-12   0  -0.033696  0.040217  LLChgs 4/5
1   ATHX  LLBCP2  2021-02-12   0  -0.015267  0.026718  LLChgs 4/5
0   WATT  LLBCP2  2021-02-12   0  -0.025412  0.023529  LLChgs 2/5
3     NH  LLBCP2  2021-02-12   0  -0.012708  0.016667  LLChgs 1/5
6     QS  LLBCP2  2021-02-11   1  -0.006061  0.009428  LLChgs 3/5
5     XM  LLBCP2  2021-02-11   1  -0.013478  0.002391  LLChgs 4/5

In [4]:
# HHBCN Last 2 Day
df[df.HqType == 'HHBCN2'].sort_values(by='CCChg', ascending=False)

  Symbol  HqType        Date  No  HqTypeChg    CCChg
4   SNDL  HHBCN2  2021-02-11   1   0.311864 -0.19322

In [2]:
symbol = 'ATHX'
csv = pd.read_csv(('../' + HqCsvRepo).format(symbol), header=0, index_col=[0], parse_dates=True)
hqop.hq_addCols(csv)
csv.tail(3)

,High,Low,Open,Close,Volume,Adj Close,PrvClose,PrvLow,PrvHigh,PrvVolume,CCChg,LLChg,HHChg,VVChg,No
Date,,,,,,,,,,,,,,,
2021-02-10,2.92,2.61,2.76,2.72,2985200,2.72,2.76,2.71,2.83,3004100.0,-0.014493,-0.036232,0.032609,-18900.0,2
2021-02-11,2.75,2.58,2.74,2.62,2910400,2.62,2.72,2.61,2.92,2985200.0,-0.036765,-0.011029,-0.062500,-74800.0,1
2021-02-12,2.74,2.54,2.63,2.69,2287200,2.69,2.62,2.58,2.75,2910400.0,0.026718,-0.015267,-0.003817,-623200.0,0

In [10]:
df = csv
df[(df.LLChg < 0) & (df.No < 5)].shape[0] #csv[(csv.LLChg < 0) & (csv.No < 5)]#.shape[0]

4